version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: msg_chatbot_whatsapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   depends_on:
  #     - db
  #   environment:
  #     OPENAI_API_KEY: ${OPENAI_API_KEY}
  #     WHATSAPP_API_KEY: ${WHATSAPP_API_KEY}
  #     PHONE_NUMBER_ID: ${PHONE_NUMBER_ID}
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASS: postgres
  #     DB_NAME: msg_chatbot_whatsapp
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - .env
